javascript:
(
	function(j,f,dom)
	{

		j=['https://sgimera.github.io/mai_RatingAnalyzer/scripts/mai_in_lv_milk.js',
		   'https://ymleung45.github.io/maimaiTesting/cal.js',
		   'https://ymleung45.github.io/maimaiTesting/body.js'];
		dom='';
		console.log(dom);
		f=function(s,u)
		{
			if(j.length==0)
			{
				return;
			}
			u=dom+j.shift()+'?'+Date.now();
			s=document.createElement('script');
			document.body.appendChild(s);
			s.charset='UTF-8';
			s.addEventListener('load',f);
			s.src=u;
		};
		(document.readyState=='loading')?document.addEventListener('DOMContentLoaded',f):f();
	}
)();
